module.exports = {
  dbHost: process.env.DB_HOST || 'tx',
  dbDatabase: process.env.DB_DATABASE || 'tx',
  dbUser: process.env.DB_USER || 'tx',
  dbPassword: process.env.DB_PASSWORD || 'tx',
  dbPort: process.env.DB_PORT || 5432,
  dbString: 'postgresql://PavaoZornija1:Gxoy6OqwiP1n@ep-steep-poetry-48615223.us-east-2.aws.neon.tech/taxi?sslmode=require',
  port: process.env.PORT || 5000,
  wsPort: process.env.WS_PORT || 7000,
  isDev: process.env.IS_DEV === 'true' || false,
  isTest: process.env.IS_TEST === 'true' || false,
  jwtIssuer: 'TaxiApp',
  jwtAudience: 'AppUsers',
  apiUrl: process.env.REDIRECT_URL_API || 'http://localhost:5000',
  pubKey: 'taxiApp',
  privKey: 'taxiAppProd',
  AWS_BUCKET: process.env.AWS_BUCKET || "cyclic-delightful-hen-umbrella-eu-west-1",
  AWS_REGION: process.env.AWS_REGION,
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
  AWS_SESSION_TOKEN: process.env.AWS_SESSION_TOKEN
};
